spring.application.name=Smart-course-management

spring.datasource.url = jdbc:mysql://localhost:3306/smart_course_management
spring.datasource.username = root
spring.datasource.password = SatyajitDB@1205

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.highlight_sql=true

logging.level.org.hibernate.orm.jdbc.bind=trace
